import localFont from "next/font/local";
import "./globals.css";
import { EB_Garamond } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const alegreya = localFont({
  src: "./fonts/Alegreya.woff",
  variable: "--font-alegreya",
  weight: "100 900",
});

const ebGaramond = EB_Garamond({
  weight: '800',
  subsets: ['latin'],
  variable: '--font-eb-garamond',
  display: 'swap'
});

// Configure Alegreya with specific weights if needed
/*const alegreya = Alegreya({
  weight: '800',
  subsets: ['latin'],
  variable: '--font-alegreya',
  display: 'swap',
});*/

export const metadata = {
  title: "fabceylon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export { ebGaramond, alegreya };